### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by bencbernstein** [Classical-SB/aquifier#48]
- bug 1 in console log: "error during service worker registration. DOM exception: only secure origins are allowed registerServiceWorker js:71 https://goo.gl/Y0ZkNV"

- bug 2 it seems that nicknames that contain punctuation are getting silently rejected. I think the problem was that the nickname entered was Mia M. and contained a period.  “Uncaught (in promise) error: reference.update failed: first argument contains an invalidy key (Mia M.) in oath Keys must be non-empty strings and can’t contain “.”, “#”, “$”...

**Comment by cashmonides** [comment]
bug 3: no question served (console log: cannot read property split on undefined)
![split_on_undefined](https://user-images.githubusercontent.com/9938643/31526566-a8f03b84-af95-11e7-8bea-606f1122aab2.jpg)
bug 4: connector letter getting deleted, can't advance (the O in LITH.O.PHYTE) (console log: error during service worker registration)
![connector_missing](https://user-images.githubusercontent.com/9938643/31526557-a176b856-af95-11e7-8cc4-ed0f6d9bd748.jpg)
